Repository belsterns/eztest.ai, pull requests merged in 2025-03, with the labels that each got.

#12 API for CRUD of workspaces
  prisma/migrations/20250228064009_added_workspace_and_user_workspace_tables/migration.sql
  prisma/schema.prisma
  src/app/backend/api/v1/workspace/[workspace_uuid]/route.ts
  src/app/backend/api/v1/workspace/route.ts
  src/app/backend/constants/StaticMessages.ts
  src/app/backend/controllers/workspace/workspace.controller.ts
  src/app/backend/infrastructure/dtos/WorkspaceRequestDto.ts
  src/app/backend/services/workspace/user.workspace.service.ts
  src/app/backend/services/workspace/workspace.service.ts
  src/app/backend/utils/exceptions.ts
  src/app/backend/validator/WorkspaceValidator.ts
Labels: enhancement

#14 Base UI Set Up
  .env.sample
  next.config.mjs
  package-lock.json
  package.json
  src/app/backend/controllers/email/email.controller.ts
  src/app/backend/helpers/emailTransporter.ts
  src/app/frontend/components/appNavbar/appNavbar.tsx
  src/app/frontend/components/appNavbar/sideMenuMobile.tsx
  src/app/frontend/components/auth/authForm.tsx
  src/app/frontend/components/auth/content.tsx
  src/app/frontend/components/auth/forgotPassword.tsx
  src/app/frontend/components/header/header.tsx
  src/app/frontend/components/header/navBarBreadCrumbs.tsx
  src/app/frontend/components/sideMenu/menuContent.tsx
  src/app/frontend/components/sideMenu/optionsMenu.tsx
  src/app/frontend/components/sideMenu/sideMenu.tsx
  src/app/frontend/elements/button/menuButton.tsx
  src/app/frontend/elements/card/authFormcard.tsx
  src/app/frontend/pages/(app)/layout.tsx
  src/app/frontend/pages/(app)/repositories/layout.tsx
  src/app/frontend/pages/(app)/repositories/page.tsx
  src/app/frontend/pages/(app)/users/layout.tsx
  src/app/frontend/pages/(app)/users/page.tsx
  src/app/frontend/pages/(app)/workspaces/layout.tsx
  src/app/frontend/pages/(app)/workspaces/page.tsx
  src/app/frontend/pages/(auth)/logIn/layout.tsx
  src/app/frontend/pages/(auth)/logIn/page.tsx
  src/app/frontend/pages/(auth)/register/layout.tsx
  src/app/frontend/pages/(auth)/register/page.tsx
  src/app/frontend/pages/layout.tsx
  src/app/frontend/services/themeprovidor/provider.tsx
  src/app/frontend/services/themeprovidor/theme/AppTheme.tsx
  src/app/frontend/services/themeprovidor/theme/ColorModeIconDropdown.tsx
  src/app/frontend/services/themeprovidor/theme/ColorModeSelect.tsx
  src/app/frontend/services/themeprovidor/theme/CustomIcons.tsx
  src/app/frontend/services/themeprovidor/theme/customizations/dataDisplay.tsx
  src/app/frontend/services/themeprovidor/theme/customizations/dataGrid.ts
  src/app/frontend/services/themeprovidor/theme/customizations/datePickers.ts
  src/app/frontend/services/themeprovidor/theme/customizations/index.ts
  src/app/frontend/services/themeprovidor/theme/customizations/inputs.tsx
  src/app/frontend/services/themeprovidor/theme/customizations/navigation.tsx
  src/app/frontend/services/themeprovidor/theme/customizations/surfaces.ts
  src/app/frontend/services/themeprovidor/theme/themePrimitives.ts
  src/app/layout.tsx
Labels: enhancement

#18 Standardize UI for api calls and in page alerts
  src/app/backend/types/next-auth.d.ts
  src/app/frontend/components/header/navBarBreadCrumbs.tsx
  src/app/frontend/components/sideMenu/sideMenu.tsx
  src/app/frontend/constants/app.ts
  src/app/frontend/contexts/alertContext.tsx
  src/app/frontend/elements/alert/alert.tsx
  src/app/frontend/elements/loader/backDropLoader.tsx
  src/app/frontend/elements/loader/loader.tsx
  src/app/frontend/hooks/useAPICall.tsx
  src/app/frontend/hooks/useAlertManager.tsx
  src/app/frontend/pages/(app)/repositories/page.tsx
  src/app/frontend/pages/(app)/users/page.tsx
  src/app/frontend/pages/(app)/workspaces/page.tsx
  src/app/frontend/pages/(auth)/logIn/layout.tsx
  src/app/frontend/pages/(auth)/logIn/page.tsx
  src/app/frontend/pages/(auth)/register/page.tsx
  src/app/frontend/pages/layout.tsx
  src/app/frontend/services/themeprovidor/theme/customizations/dataGrid.ts
  src/app/frontend/services/themeprovidor/theme/customizations/inputs.tsx
Labels: enhancement

#24 Build Issue on unused token
  src/app/backend/controllers/repositories/repository.controller.ts
  src/app/frontend/components/header/navBarBreadCrumbs.tsx
Labels: bug

#26 feat(EZ-06): Include repo url in repository response
  next.config.mjs
  prisma/migrations/20250308074733_include_repo_url/migration.sql
  prisma/schema.prisma
  src/app/backend/api/v1/workspace/[workspace_uuid]/route.ts
  src/app/backend/controllers/repositories/repository.controller.ts
  src/app/backend/services/repositories/repository.service.ts
Labels: enhancement

#22 Implementation for workspace UI CRUD operations
  src/app/frontend/components/formDrawer/drawer.tsx
  src/app/frontend/components/formDrawer/form.tsx
  src/app/frontend/components/header/navBarBreadCrumbs.tsx
  src/app/frontend/components/sideMenu/menuContent.tsx
  src/app/frontend/components/sideMenu/optionsMenu.tsx
  src/app/frontend/components/workspaces/allWorkspaces.tsx
  src/app/frontend/components/workspaces/workspaceCard.tsx
  src/app/frontend/components/workspaces/workspaceTabs.tsx
  src/app/frontend/elements/alert/alert.tsx
  src/app/frontend/pages/(app)/workspaces/[uuid]/layout.tsx
  src/app/frontend/pages/(app)/workspaces/[uuid]/repositories/page.tsx
  src/app/frontend/pages/(app)/workspaces/[uuid]/users/page.tsx
  src/app/frontend/pages/(app)/workspaces/layout.tsx
  src/app/frontend/pages/(app)/workspaces/page.tsx
  src/app/frontend/pages/(auth)/register/page.tsx
  src/app/frontend/pages/layout.tsx
Labels: enhancement

#25 Implement authentication middleware
  next.config.ts
  src/app/frontend/components/auth/authForm.tsx
  src/app/frontend/pages/(auth)/logIn/page.tsx
  src/app/frontend/services/themeprovidor/theme/ColorModeSelect.tsx
  src/middleware.ts
Labels: enhancement

#36 Removed code for all repositories
  src/app/frontend/components/repositories/repoTable.tsx
  src/app/frontend/components/repositories/repositories.tsx
Labels: enhancement

#49 Fixed sidebar menu highlighting for selected item
  src/app/frontend/components/sideMenu/menuContent.tsx
Labels: bug

#46 Implementation of multi line input field and updated the workspace de…
  src/app/frontend/components/formDrawer/form.tsx
  src/app/frontend/components/workspaces/allWorkspaces.tsx
  src/app/frontend/services/themeprovidor/theme/customizations/inputs.tsx
Labels: enhancement

#47 Implemented redirection to workspaces on clicking logo
  src/app/frontend/components/sideMenu/sideMenu.tsx
Labels: enhancement

#52 Updated ui for workspace tabs
  src/app/frontend/components/workspaces/workspaceTabs.tsx
  src/app/frontend/pages/(app)/workspaces/[uuid]/workspace-members/page.tsx
Labels: enhancement

#57 Updated ui for form drawer
  src/app/frontend/components/formDrawer/drawer.tsx
Labels: enhancement

#62 Fix/update seo page title for workspace page
  src/app/frontend/contexts/workspaceContext.tsx
  src/app/frontend/pages/(app)/workspaces/[uuid]/layout.tsx
  src/app/frontend/pages/(app)/workspaces/[uuid]/repositories/page.tsx
  src/app/frontend/pages/(app)/workspaces/[uuid]/workspace-members/page.tsx
Labels: bug

#61 Feat/update repository table UI
  src/app/frontend/components/repositories/repoTable.tsx
  src/app/frontend/components/repositories/repositories.tsx
Labels: enhancement

#65 Build agent interaction APIs - Get all branches from a repo
  src/app/backend/api/v1/agent/create-new-file/route.ts
  src/app/backend/api/v1/agent/get-all-branches/route.ts
  src/app/backend/api/v1/agent/update-existing-file/route.ts
  src/app/backend/controllers/agent/agent.controller.ts
  src/app/backend/controllers/webhook/fullRepoWebhook.controller.ts
  src/app/backend/infrastructure/dtos/CreateNewFileRequestDto.ts
  src/app/backend/infrastructure/dtos/GetAllBranchesRequestDto.ts
  src/app/backend/infrastructure/dtos/UpdateExistingFileRequestDto.ts
  src/app/backend/infrastructure/factory/GitHubProvider.ts
  src/app/backend/infrastructure/factory/GitLabProvider.ts
  src/app/backend/infrastructure/factory/GitProvider.ts
  src/app/backend/infrastructure/factory/GiteaProvider.ts
  src/app/backend/services/repositories/repository.service.ts
  src/app/backend/utils/user.auth.ts
  src/app/backend/validator/AgentInteractionAPIValidator.ts
  src/app/frontend/components/formDrawer/form.tsx
  src/middleware.ts
Labels: Backend

#72 Updated middleware to handle webhook api's
  src/middleware.ts
Labels: bug

#71 Updated login page layout and delete popup
  src/app/frontend/elements/popup/deleteConfirmation.tsx
  src/app/frontend/pages/(auth)/login/layout.tsx
  src/app/frontend/pages/(auth)/login/page.tsx
Labels: bug, enhancement
